### ISSUE TITLE
accounts_password_last_change_is_in_past test scenarios results in unknown for containers

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#10212]
#### Description of problem:

When testing the `accounts_password_last_change_is_in_past` in containers the test scenarios are resulting in `unknown`.
It is caused because the containers used in the test don't have some commands. This was discussed in the and waived by me in https://github.com/ComplianceAsCode/content/pull/10031.

Since it is also appearing in Productization tests, I believe it is feasible to do small changes in the test scenario scripts instead of waiving the rule.
I will take a look again.

#### SCAP Security Guide Version:

master as of 2023-02-13

#### Operating System Version:

RHEL7, RHEL8 and RHEL9

#### Steps to Reproduce:

1. ./build_product rhel8
2. ./tests/test_rule_in_container.sh --name ssg_test_suite --datastream build/ssg-rhel8-ds.xml --dontclean --remediate-using bash accounts_password_last_change_is_in_past

#### Actual Results:

xccdf_org.ssgproject.content_rule_accounts_password_last_change_is_in_past:unknown

#### Expected Results:

xccdf_org.ssgproject.content_rule_accounts_password_last_change_is_in_past:pass

#### Additional Information/Debugging Steps:

I reviewed this rule and is fresh in my memory, so I will take a look on this as soon as possible.

**Comment by marcusburghardt** [comment]
> The problem still manifests. More investigation is needed. The problem manifests while scanning containers through oscap-podman.

Thanks for the update @vojtapolasek . I will try to reproduce the test environment where this error manifests in order confirm if it is related to the test environment or it is a more general issue.

**Comment by marcusburghardt** [comment]
I can see this issue reproduced in CI tests for https://github.com/ComplianceAsCode/content/pull/10243 

It was not appearing when the rule was initially merged. But they are visible now when the rule was included in CIS profiles for RHEL. I will take a look but now it is easier to investigate.

**Comment by marcusburghardt** [comment]
This should be the issue.
```
W: oscap:     Entity name 'value' from state (id: 'oval:ssg-state_accounts_password_last_change_time_diff:ste:1') not found in item (id: '107586219').
xccdf_org.ssgproject.content_rule_accounts_password_last_change_is_in_past:unknown
```

**Comment by marcusburghardt** [comment]
This issue should be fixed by https://github.com/ComplianceAsCode/content/pull/10243

**Comment by marcusburghardt** [comment]
https://github.com/ComplianceAsCode/content/pull/10243 was merged today. Let't wait the new round of tests to confirm the issue was fixed.

**Comment by mildas** [comment]
Issue still manifests in all RHELs
`xccdf_org.ssgproject.content_rule_accounts_password_last_change_is_in_past:unknown`
