### ISSUE TITLE
file_permission_user_init_files_root is misaligned with RHEL 9 STIG

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#11778]
#### Description of problem:

The content is misaligned with an external (third party) content that targets the same policy - typically, this means that a system hardened by our content doesn't pass the scan by the external content.
STIG: https://stigaview.com/products/rhel9/v1r2/RHEL-09-232045/

#### Details:

The problem is that our rule is restricted only to certain init files. They are defined by a respective variable var_user_initialization_files_regex.
The default value of this variable applies the rule only to small subset of initialization files. It does not include for example .bash_logout. STIG SCAP has no exceptions and therefore fails.
It should be enough to change this variable.

The misalignment affects these profiles:

- stig

The misalignment affects these rules:

- file_permission_user_init_files_root

#### Outcome:

- our content passes
- DISA content fails

#### SCAP Security Guide Version:

from master branch as of 2024-03-30

####  External Content's Version:

RHEL 9, v1r1

**Comment by Mab879** [comment]
Please add more information.

**Comment by marcusburghardt** [comment]
It is related to https://github.com/ComplianceAsCode/content/pull/11729

**Comment by vojtapolasek** [comment]
I found the culprit. the OVAL check oval:mil.disa.stig.defs:def:230325 checks two things:
1. permissions of local initialization files within the home directory of the user with id 0
2. permissions of local initialization files within home directories of non-system users (id > 999)

The test fails in case there is no directory found in point 2 above. I think this should be fixed on DISA side.

**Comment by marcusburghardt** [comment]
It seems fixed by https://github.com/ComplianceAsCode/content/pull/11890

**Comment by vojtapolasek** [comment]
It is not fixed. ACtually we can't fix it, DISA needs to change their SCAP.  See my comment above.

**Comment by Mab879** [comment]
Fixed.
